name: SignalK Plugin CI

on:
  push:
    branches: [master, modern-signalk-plugin]
  pull_request:
    branches: [master]

jobs:
  test:
    uses: SignalK/signalk-server/.github/workflows/plugin-ci.yml@master
